GET http://localhost:3000/planets

###

Get http://localhost:3000/planets/5d3e0db7cb4be0bfc4c25ff9

Get http://localhost:3000/planets/name/Tatooine

QUERY

Get http://localhost:3000/planets?id=5d3e0db7cb4be0bfc4c25ff9

Get http://localhost:3000/planets?name=Tatooine

###


POST http://localhost:3000/planets
Content-Type: application/json

{
  "name": "Lizzy",
  "subscribedChannel": "Bennetts Channel"
}

###
DELETE http://localhost:3000/planets/5d3e0db7cb4be0bfc4c25ff9

###
PATCH http://localhost:3000/planets/5d3e144ecb4be0bfc4c25ffa
Content-Type: application/json

{
  "name": "Tommy"
}
